apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-app-base
spec:
  replicas: 8
  selector:
    matchLabels:
      app: web-app-base
  template:
    metadata:
      labels:
        app: web-app-base
    spec:
      containers:
      - name: web-app-base
        image: askull1/ob_deploy:20240422
        ports:
        - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: web-app-service
  labels:
    app: web-app-base
spec:
  selector:
    app: web-app-base
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
  type: ClusterIP
