apiVersion: apps/v1
kind: Deployment
metadata:
  name: canary-app
spec:
  replicas: 8
  selector:
    matchLabels:
      app: canary-app
  template:
    metadata:
      labels:
        app: canary-app
    spec:
      containers:
      - name: canary-app
        image: askull1/ob_deploy:latest
        ports:
        - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: web-app-canary
  labels:
    app: canary-app
spec:
  selector:
    app: canary-app
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
  type: ClusterIP
